### ISSUE TITLE
Connection to MySQL 8 failed - jdbc driver requires upgrade

### ISSUE THREAD

**Issue by duritong** [appuio/example-spring-boot-helloworld#9]
In OCP 4 the mysql-persistent template provisions a MySQL 8.

However, the jdbc driver in the current released image is failing with:

```
Caused by: java.lang.NullPointerException
        at com.mysql.jdbc.ConnectionImpl.getServerCharset(ConnectionImpl.java:2997)
        at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1934)
```

See https://bugs.mysql.com/bug.php?id=86221 for background

Downgrading MySQL to the lower version (5.7) fixes the issue.

But to support the default MySQL Version deployed throught he template, the jdbc connector should be upgraded.

**Comment by phil-pona** [comment]
I think we should create a OCP 4 Branch and update the driver in this version, what do you think @chrira ?

**Comment by chrira** [comment]
> I think we should create a OCP 4 Branch and update the driver in this version, what do you think @chrira ?

Yes, that is a good idea.
Hibernate 5.3.1 should support MySQL 8.
Eventually updating SpringBoot can help.

**Comment by phil-pona** [comment]
should work now, can you verify @duritong ?

**Comment by chrira** [comment]
It does now work with ocp4 and MySql 8
Thanks!
